[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/assets/wasm/*"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-STX-Track-Key, X-STX-Items-Bump-Key, X-STX-Admin-Key"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Cache-Control = "no-store"
